<?php $__env->startSection('content'); ?>
<title>
<?php $__env->startSection('title','KGT ERP | Un-Posted / Pending Receipts'); ?>
</title>
<div class="container-fluid bg-white box-shadow  pt-4 pb-4" id="app">
        <div style="display :none" class="row input-daterange">
            <div class="col-md-4">
                <input type="date" name="from_date" id="from_date" class="form-control" placeholder="From Date" >
            </div>
            <div class="col-md-4">
                 <input type="date" name="to_date" id="to_date" class="form-control" placeholder="To Date" >

            </div>
            <div class="col-md-4">
                 <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                 <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
            </div>

        </div>
        <div class="row" style="padding:15px ">
            <div class="col-md-10">
                <select name=""  class="form-control form-control-sm" id="">
                    <option value="1">K.G. TRADERS (PVT) LTD.</option>
                    <option value="4">KGT Business Solutions</option>
                    <option value="5">Muhammad Khalid Collateral Management Co.</option>
                    <option value="6">Prism Surveyors (Pvt) Ltd.</option>
                    <option value="7">Raddium Technology</option>
                    <option value="8">VHR Services</option>
                </select>
            </div>
            <div class="col-md-2">
                 <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                 <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
            </div>
        </div>
        <table class="table display"  id="myTable" >
        <thead class="thead-dark">
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Receipt No </th>
            <th scope="col">Received On</th>
            <th scope="col">Type</th>
            <th scope="col">Number</th>
            <th scope="col">Date</th>
            <th scope="col">Amount</th>
            <th scope="col">Generated By</th>
            <th scope="col">Action </th>


            </tr>
        </thead>
        <tbody>
        
        </tbody>
        </table>


        </div>



        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script  type="text/javascript">
    $(function(){


      load_data();


      function load_data(from_date='',to_date='')
      {

        var table =$('#myTable').DataTable({
        serverSide: true,
        processing: true,
        ajax:{
          url: "/allReceiptsForUnPosted",
          data:{from_date:from_date,to_date:to_date}
        },
        columns: [
            {data: 'id', name: 'id'},
            {data: 'receipt_id', name: 'receipt_id'},
            {data: 'receipt_date', name: 'receipt_date'},
            {data: 'method', name: 'method'},
            {data: 'instrument_number', name: 'instrument_number'},
            {data: 'deposit_date', name: 'deposit_date'},
            {data: 'amount', name: 'amount'},
            {data: 'user_name', name: 'user_name'},
            {data: 'action', name: 'action', orderable: false, searchable: false}


        ],
           order: [[0,'desc']],







    });


      }

        $('#filter').click(function(){
          var from_date =$('#from_date').val();
          var to_date =$('#to_date').val();
            if(from_date != '' &&  to_date != '')
            {
              $('#myTable').DataTable().destroy();
              load_data(from_date,to_date);
            }
            else{
              alert('Both Date is required');
            }
        });

        $('#refresh').click(function(){
            $('#from_date').val('');
            $('#to_date').val('');
            $('#myTable').DataTable().destroy();
            load_data();
        });


    });


</script>
<script>
 function getReceipt(id){
    $.ajax({
  url: "/getReceiptById/" + id,
  method:'GET',
  dataType:'json'
}).done(function(data) {
    $('#receiptID').val(data[0].receipt_id);
    $('#receipGenerated').val(data[0].created_at);
    $('#receiptInstrument').val(data[0].method);
    $('#selectedReceipt').val(data[0].id);
    $('#receiptBills').val(data[0].bills_id);
    $('#receiptJobs').val(data[0].jobs_number);
    $('#receiptNet').val(data[0].net);
    $('#receiptBillAmount').val(data[0].amount);
    $('#receiptSalesTax').val(data[0].sales_tax);
    $('#receiptTaxableAmount').val(data[0].taxable_amount);
    $('#receiptBankCharges').val(data[0].bank_charges);
    $('#receiptReceivedOn').val(data[0].receipt_date);
    $('#receiptDepositDate').val(data[0].deposit_date);
    $('#receiptDepositIn').val(data[0].bank_account);
    $('#receiptInstrumentNumber').val(data[0].instrument_number);
    $('#receiptInstrumentDate').val(data[0].instrument_date);
    $('#receiptSlipNo').val(data[0].slip_number);
    $('#receiptRemarks').val(data[0].remarks);
    $('#frame1').prop('src',data[0].client_copy);
    $('#frame2').prop('src',data[0].deposit_copy);

    var status=data[0].status;


    if(status=='Rejected' )
    {
        $('#approve').show();
        $('#reject').hide();
    }
    if(status=='Approved' )
    {
        $('#reject').show();
        $('#approve').hide();

    }

    if(status=='Pending' )
    {
        $('#reject').show();
        $('#approve').show();
    }

});

 }



</script>
<script>
function approveReceipt(){
    var rid=[];
    var bills=[];
    var receiptID=$('#selectedReceipt').val();
    var receiptBills=$('#receiptBills').val();

    rid.push(receiptID);
    bills.push(receiptBills);


    $.ajax({
  url: "/approveBill",
  method:'POST',
  data:{
      bills:bills,
      rid:rid,
      "_token": "<?php echo e(csrf_token()); ?>"

  }
}).done(function() {

    alert('Receipt Approved');
    $('#exampleModal').modal('hide');
    $('#myTable').DataTable().ajax.reload();

});

 }



 function rejectReceipt(){
    var rid=[];
    var bills=[];
    var receiptID=$('#selectedReceipt').val();
    var receiptBills=$('#receiptBills').val();

    rid.push(receiptID);
    bills.push(receiptBills);


    $.ajax({
  url: "/rejectBill",
  method:'POST',
  data:{
      bills:bills,
      rid:rid,
      "_token": "<?php echo e(csrf_token()); ?>"

  }
}).done(function() {

    alert('Receipt Approved');
    $('#exampleModal').modal('hide');
    $('#myTable').DataTable().ajax.reload();
});

 }
</script>

<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\kgt-erp\resources\views/Bill/posts.blade.php ENDPATH**/ ?>