@extends('layouts.app')

@section('content')
<title>
@section('title','KGT ERP | Receipts')
</title>
<div class="container-fluid bg-white box-shadow  pt-4 pb-4" id="app">
        <!-- <div class="row input-daterange">
            <div class="col-md-4">
                <input type="date" name="from_date" id="from_date" class="form-control" placeholder="From Date" >
            </div>
            <div class="col-md-4">
                 <input type="date" name="to_date" id="to_date" class="form-control" placeholder="To Date" >

            </div>
            <div class="col-md-4">
                 <button type="button" name="filter" id="filter" class="btn btn-primary">Filter</button>
                 <button type="button" name="refresh" id="refresh" class="btn btn-default">Refresh</button>
            </div>
            <div class="col-md-8 mt-3">
                <select name="" id="" class="form-control form-control-sm">
                    <option value="">Karachi</option>
                    <option value="">Lahore</option>
                    <option value="">Islamabad</option>
                    <option value="">Peshawar</option>
                    <option value="">Quetta</option>
                </select>
            </div>
            <div class="col-md-12">
                <div class="row" style="padding: 17px;">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="status" id="status" value="Pending">
                        <label class="form-check-label" for="inlineRadio1">Pending</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="status" id="status" value="Approved">
                        <label class="form-check-label" for="inlineRadio2">Approved</label>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="row" style="padding: 17px;">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="instrument" id="instrument" value="1">
                        <label class="form-check-label" for="inlineRadio1">Cash</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="instrument" id="instrument" value="2">
                        <label class="form-check-label" for="inlineRadio1">Cheque</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="instrument" id="instrument" value="3">
                        <label class="form-check-label" for="inlineRadio1">Demand Draft</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="instrument" id="instrument" value="4">
                        <label class="form-check-label" for="inlineRadio1">OnLine Transfer</label>
                    </div>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="status" id="status" value="5">
                        <label class="form-check-label" for="inlineRadio2">Pay Order</label>
                    </div>
                </div>
            </div>

        </div>  --!>
        <table class="table display table-responsive"  id="myTable" >
        <thead class="thead-dark">
            <tr>
            <th scope="col">Id</th>
            <th scope="col">Receipt ID </th>
            <th scope="col">Receipt Date </th>
            <th scope="col">Region </th>
            <th scope="col">Instrument</th>
            <th scope="col">Receivable</th>
            <th scope="col">Net</th>
            <th scope="col">Tax</th>
            <th scope="col">Generated By</th>
            <th scope="col">Status </th>
            <th scope="col">Action </th>


            </tr>
        </thead>
        <tbody>
        <tfoot>
        <tr>

            <th id="rec" colspan="6"   style="text-align:right">/th>
            <th id="total"   style="text-align:right"></th>
            <th id="tax"   style="text-align:right"></th>
            <th></th>
            <th></th>
            <th></th>

        </tr>
    </tfoot>
        </tbody>
        </table>


        </div>


        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Receipt Viewer</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form>
            <div class="row">
                <div class="col-md-8">
                    <label for="">  ID</label>
                    <input type="hidden" id="selectedReceipt" readonly class="form-control">

                </div>
                <div class="col-md-8">
                    <label for=""> Receipt ID</label>
                    <input type="text" id="receiptID" readonly class="form-control">

                </div>
                <div class="col-md-4">
                    <label for="">Generated On</label>
                    <input type="text" id="receipGenerated" readonly class="form-control">
                </div>
            </div><br>
            <div class="row">
                <div class="col-md-12">
                    <label for=""> Instrument</label>
                    <input type="text" readonly id="receiptInstrument" class="form-control">
                </div>
            </div> <br>
            <div class="row">
                <div class="col-md-12">
                    <label for="">Bills</label>
                    <input type="hidden" readonly id="receiptBills" class="form-control">
                    <input type="text" readonly id="receiptJobs" class="form-control">
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <label for="">Net Amount</label>
                    <input type="text" readonly id="receiptNet" class="form-control">
                    <br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label for="">Bill Amount</label>
                    <input type="text" readonly id="receiptBillAmount" class="form-control">
                </div>
                <div class="col-md-3">
                    <label for="">Sales Tax</label>
                    <input type="text" readonly id="receiptSalesTax" class="form-control">
                </div>
                <div class="col-md-3">
                    <label for="">Taxable Amount</label>
                    <input type="text" readonly id="receiptTaxableAmount" class="form-control">
                </div>
                <div class="col-md-3">
                    <label for="">Bank Charges</label>
                    <input type="text" readonly id="receiptBankCharges" class="form-control">
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-md-6">

                    <label for=""> Received On</label>
                    <input type="date" readonly id="receiptReceivedOn" class="form-control">
                    <br>
                    <label for=""> Instrument Number</label>
                    <input type="text" readonly id="receiptInstrumentNumber" class="form-control">
                    <br>
                    <label for=""> Instrument Date</label>
                    <input type="date" readonly id="receiptInstrumentDate" class="form-control">


                </div>
                <div class="col-md-6">


                    <label for="">Deposit Date</label>
                    <input type="date" readonly id="receiptDepositDate" class="form-control">
                    <br>
                    <label for="">Deposit In</label>
                    <input type="text" readonly id="receiptDepositIn" class="form-control">
                    <br>
                    <label for="">Slip No</label>
                    <input type="text" readonly id="receiptSlipNo" class="form-control">

                </div>

            </div>
            <br>
            <div class="row">
                <div class="col-md-12">
                    <label for=""> Remarks</label>
                    <textarea style="height:120px" readonly id="receiptRemarks" class="form-control"></textarea>
                </div>
            </div>
            <div class="row mt-3">
                <label for="" class="col-md-3"> Instrument Scan</label>
                <button type="button" class="col-md-3 btn btn-primary" data-toggle="modal" data-target="#modal1">.....</button>
            </div>
            <div class="row mt-3">
                <label for="" class="col-md-3"> Dep Slip Scan</label>
                <button type="button" class="col-md-3 btn btn-primary" data-toggle="modal" data-target="#modal2">.....</button>
            </div>

      </div>
      <div class="modal-footer">
        <button type="button" type="submit" class="btn btn-success" id="approve" onclick="approveReceipt()">Approve</button>
        <button type="button" class="btn btn-danger" id="reject"  onclick="rejectReceipt()">Reject</button>
        </form>

      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Instrument Scan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <iframe id="frame1" src="" style="width:100%;height:500px" frameborder="0">

        </iframe>
      </div>

    </div>
  </div>
</div>



<div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Dep Slip Scan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <iframe id="frame2" src="" style="width:100%;height:500px" frameborder="0">

        </iframe>
      </div>

    </div>
  </div>
</div>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

<script  type="text/javascript">
    $(function(){


      load_data();


      function load_data(from_date='',to_date='',status='')
      {

        var table =$('#myTable').DataTable({
        serverSide: true,
        processing: true,
        ajax:{
          url: "/allReceipts",
          data:{
              from_date:from_date,
              to_date:to_date,
              status:status
            }
        },
        columns: [
            {data: 'id', name: 'id'},
            {data: 'receipt_id', name: 'receipt_id'},
            {data: 'receipt_date', name: 'receipt_date'},
            {data: 'city_name', name: 'city_name'},
            {data: 'method', name: 'method'},
            {data: 'amount', name: 'amount'},
            {data: 'net', name: 'net'},
            {data: 'taxable_amount', name: 'taxable_amount'},
            {data: 'user_name', name: 'user_name'},
            {data: 'status',name:'status', className : "center",render:function(status){
               if(status=="Pending"){
                return '<a href="#" class="badge badge-primary" style="font-size:15px;margin-top:5px">'+status+'</a>';
               }
               else if(status=="Approved"){
                return '<a href="#" class="badge badge-success" style="font-size:15px;margin-top:5px">'+status+'</a>';
               }
               else if(status=="Rejected"){
                return '<a href="#" class="badge badge-danger" style="font-size:15px;margin-top:5px">'+status+'</a>';
               }


            }},
            {data: 'action', name: 'action', orderable: false, searchable: false}


        ],
         order: [[0,'desc']],

          "footerCallback": function( tfoot, data, start, end, display ) {
           var api = this.api(), data;
           var intVal = function ( i ) {
               return typeof i === 'string' ?
                   i.replace(/[\$,]/g, '')*1 :
                   typeof i === 'number' ?
                       i : 0;
           };

           var amtTotal = api
               .column( 5 )
               .data()
               .reduce( function (a, b) {
                   return intVal(a) + intVal(b);
               }, 0 );
           var amtTotal1 = api
               .column( 6 )
               .data()
               .reduce( function (a, b) {
                   return intVal(a) + intVal(b);
               }, 0 );
           var amtTotal2 = api
               .column( 7 )
               .data()
               .reduce( function (a, b) {
                   return intVal(a) + intVal(b);
               }, 0 );
        $('#rec').html("<span style='color:red'>"+Number((amtTotal).toFixed(1)).toLocaleString()+"</span>");
        $('#total').html("<span style='color:red'>"+Number((amtTotal1).toFixed(1)).toLocaleString()+"</span>");
        $('#tax').html("<span style='color:red'>"+Number((amtTotal2).toFixed(1)).toLocaleString()+"</span>");
      },





    });


      }

        $('#filter').click(function(){
          var from_date =$('#from_date').val();
          var to_date =$('#to_date').val();
          var status =$("#status:checked").val();
            if(from_date != '' &&  to_date != '')
            {
              $('#myTable').DataTable().destroy();
              load_data(from_date,to_date,status);

            }
            else{
              alert('Both Date is required');
            }
        });

        $('#refresh').click(function(){
            $('#from_date').val('');
            $('#to_date').val('');
            $("#status:checked").prop('checked', false);
            $('#myTable').DataTable().destroy();
            load_data();
        });


    });


</script>
<script>
 function getReceipt(id){
    $.ajax({
  url: "/getReceiptById/" + id,
  method:'GET',
  dataType:'json'
}).done(function(data) {
    $('#receiptID').val(data[0].receipt_id);
    $('#receipGenerated').val(data[0].created_at);
    $('#receiptInstrument').val(data[0].method);
    $('#selectedReceipt').val(data[0].id);
    $('#receiptBills').val(data[0].bills_id);
    $('#receiptJobs').val(data[0].jobs_number);
    $('#receiptNet').val(data[0].net);
    $('#receiptBillAmount').val(data[0].amount);
    $('#receiptSalesTax').val(data[0].sales_tax);
    $('#receiptTaxableAmount').val(data[0].taxable_amount);
    $('#receiptBankCharges').val(data[0].bank_charges);
    $('#receiptReceivedOn').val(data[0].receipt_date);
    $('#receiptDepositDate').val(data[0].deposit_date);
    $('#receiptDepositIn').val(data[0].bank_account);
    $('#receiptInstrumentNumber').val(data[0].instrument_number);
    $('#receiptInstrumentDate').val(data[0].instrument_date);
    $('#receiptSlipNo').val(data[0].slip_number);
    $('#receiptRemarks').val(data[0].remarks);
    $('#frame1').prop('src',data[0].client_copy);
    $('#frame2').prop('src',data[0].deposit_copy);

    var status=data[0].status;


    if(status=='Rejected' )
    {
        $('#approve').show();
        $('#reject').hide();
    }
    if(status=='Approved' )
    {
        $('#reject').show();
        $('#approve').hide();

    }

    if(status=='Pending' )
    {
        $('#reject').show();
        $('#approve').show();
    }

});

 }



</script>
<script>
function approveReceipt(){
    var rid=[];
    var bills=[];
    var receiptID=$('#selectedReceipt').val();
    var receiptBills=$('#receiptBills').val();

    rid.push(receiptID);
    bills.push(receiptBills);


    $.ajax({
  url: "/approveBill",
  method:'POST',
  data:{
      bills:bills,
      rid:rid,
      "_token": "{{ csrf_token() }}"

  }
}).done(function() {

    alert('Receipt Approved');
    $('#exampleModal').modal('hide');
    $('#myTable').DataTable().ajax.reload();

});

 }



 function rejectReceipt(){
    var rid=[];
    var bills=[];
    var receiptID=$('#selectedReceipt').val();
    var receiptBills=$('#receiptBills').val();

    rid.push(receiptID);
    bills.push(receiptBills);


    $.ajax({
  url: "/rejectBill",
  method:'POST',
  data:{
      bills:bills,
      rid:rid,
      "_token": "{{ csrf_token() }}"

  }
}).done(function() {

    alert('Receipt Approved');
    $('#exampleModal').modal('hide');
    $('#myTable').DataTable().ajax.reload();
});

 }
</script>

@endsection
